<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Skytech.Aplicacao\Skytech.Aplicacao.csproj" />
    <ProjectReference Include="..\Skytech.Dominio\Skytech.Dominio.csproj" />
    <ProjectReference Include="..\Skytech.Ioc\Skytech.Ioc.csproj" />
  </ItemGroup>

</Project>
